import type { MarineLifeText } from './marine-life'

// 繁體中文（台灣）— display labels for the marine-life vocabulary. The English
// name stays the identifier (it makes the gallery slug); only the label shown to
// a reader is translated. Same keys as MARINE_LIFE — a parity test enforces it.

export const marineLifeZhTW: MarineLifeText = {
  Nudibranchs: '海蛞蝓',
  Cowries: '寶螺',
  'Moray eels': '裸胸鯙',
  Scorpionfish: '石狗公',
  Lionfish: '獅子魚',
  Frogfish: '躄魚',
  Seahorses: '海馬',
  'Pygmy seahorses': '豆丁海馬',
  Octopus: '章魚',
  Cuttlefish: '烏賊',
  Squid: '魷魚',
  Clownfish: '小丑魚',
  Anthias: '金花鱸',
  Damselfish: '雀鯛',
  Butterflyfish: '蝴蝶魚',
  Angelfish: '神仙魚',
  Wrasses: '隆頭魚',
  'Napoleon wrasse': '拿破崙魚',
  Parrotfish: '鸚哥魚',
  Surgeonfish: '刺尾鯛',
  Trumpetfish: '喇叭魚',
  Pufferfish: '河魨',
  Boxfish: '箱魨',
  'Flying gurnards': '飛角魚',
  Groupers: '石斑魚',
  Snappers: '笛鯛',
  Grunts: '石鱸',
  Sweetlips: '胡椒鯛',
  Fusiliers: '烏尾鮗',
  Sardines: '沙丁魚',
  'Reef fish': '礁岩魚類',
  Barracuda: '梭魚',
  Trevally: '平鰺',
  Jacks: '鰺魚',
  Amberjacks: '紅甘鰺',
  Tuna: '鮪魚',
  'Pelagic fish': '洄游魚類',
  'Reef sharks': '礁鯊',
  'Whale sharks': '鯨鯊',
  'Hammerhead sharks': '雙髻鯊',
  'Thresher sharks': '長尾鯊',
  'Tiger sharks': '虎鯊',
  'Manta rays': '鬼蝠魟',
  'Eagle rays': '鷹魟',
  'Devil rays': '魔鬼魟',
  Stingrays: '魟魚',
  Rays: '魟',
  'Sea turtles': '海龜',
  Dolphins: '海豚',
  'Sea snakes': '海蛇',
  'Shrimp and crabs': '蝦與蟹',
  'Harlequin shrimp': '小丑蝦',
  'Mantis shrimp': '螳螂蝦',
  'Xenograpsus vent crabs': '硫磺怪方蟹',
  'Sea urchins': '海膽',
  'Hard corals': '硬珊瑚',
  'Soft corals': '軟珊瑚',
  'Leather corals': '皮革珊瑚',
  'Black coral': '黑珊瑚',
  'Sun coral': '太陽珊瑚',
  'Sea fans': '海扇',
  'Whip corals': '鞭珊瑚',
}
