import type { MarineLifeText } from './marine-life'

// 日本語（ja）— display labels for the marine-life vocabulary. The English name
// stays the identifier (it makes the gallery slug); only the label shown to a
// reader is translated. Same keys as MARINE_LIFE — a parity test enforces it.

export const marineLifeJa: MarineLifeText = {
  Nudibranchs: 'ウミウシ',
  Cowries: 'タカラガイ',
  'Moray eels': 'ウツボ',
  Scorpionfish: 'カサゴ',
  Lionfish: 'ミノカサゴ',
  Frogfish: 'カエルアンコウ',
  Seahorses: 'タツノオトシゴ',
  'Pygmy seahorses': 'ピグミーシーホース',
  Octopus: 'タコ',
  Cuttlefish: 'コウイカ',
  Squid: 'イカ',
  Clownfish: 'クマノミ',
  Anthias: 'ハナダイ',
  Damselfish: 'スズメダイ',
  Butterflyfish: 'チョウチョウウオ',
  Angelfish: 'キンチャクダイ',
  Wrasses: 'ベラ',
  'Napoleon wrasse': 'ナポレオンフィッシュ',
  Parrotfish: 'ブダイ',
  Surgeonfish: 'ニザダイ',
  Trumpetfish: 'ヘラヤガラ',
  Pufferfish: 'フグ',
  Boxfish: 'ハコフグ',
  'Flying gurnards': 'セミホウボウ',
  Groupers: 'ハタ',
  Snappers: 'フエダイ',
  Grunts: 'イサキ',
  Sweetlips: 'コショウダイ',
  Fusiliers: 'タカサゴ',
  Sardines: 'イワシ',
  'Reef fish': 'リーフフィッシュ',
  Barracuda: 'バラクーダ',
  Trevally: 'トレバリー',
  Jacks: 'アジ',
  Amberjacks: 'カンパチ',
  Tuna: 'マグロ',
  'Pelagic fish': '回遊魚',
  'Reef sharks': 'リーフシャーク',
  'Whale sharks': 'ジンベエザメ',
  'Hammerhead sharks': 'ハンマーヘッドシャーク',
  'Thresher sharks': 'ニタリ（オナガザメ）',
  'Tiger sharks': 'イタチザメ',
  'Manta rays': 'マンタ',
  'Eagle rays': 'マダラトビエイ',
  'Devil rays': 'イトマキエイ',
  Stingrays: 'アカエイ',
  Rays: 'エイ',
  'Sea turtles': 'ウミガメ',
  Dolphins: 'イルカ',
  'Sea snakes': 'ウミヘビ',
  'Shrimp and crabs': 'エビ・カニ',
  'Harlequin shrimp': 'フリソデエビ',
  'Mantis shrimp': 'シャコ',
  'Xenograpsus vent crabs': '温泉ガニ（ゼノグラプスス）',
  'Sea urchins': 'ウニ',
  'Hard corals': 'ハードコーラル',
  'Soft corals': 'ソフトコーラル',
  'Leather corals': 'レザーコーラル',
  'Black coral': 'ブラックコーラル',
  'Sun coral': 'サンコーラル（イボヤギ）',
  'Sea fans': 'ウミウチワ',
  'Whip corals': 'ムチヤギ',
}
