// English — the master copy.
//
// Every other language file mirrors this shape exactly. Add a key here first,
// then add the same key to zh-TW.ts and ja.ts; TypeScript will refuse to build
// until they match, which is how a half-translated site never ships.
//
// Only static UI and marketing copy lives here. Text that comes from the
// database (event titles, schedules) is not translated.

export const en = {
  nav: {
    courses: 'Courses',
    sites: 'Sites',
    map: 'Map',
    photos: 'Photos',
    travel: 'Travel',
    calendar: 'Calendar',
    team: 'Team',
    gear: 'Gear',
  },
  gear: {
    title: 'Gear Sales, Service & Rental',
    subtitle:
      'Everything you need to dive — quality scuba and freediving equipment for sale or rent, plus expert servicing to keep your kit safe and dive-ready.',
    salesTitle: 'Sales',
    salesText:
      'From your first mask and fins to a full technical setup, we help you choose gear that fits you and the way you dive. Try before you buy in-store and get honest advice from working instructors — not a sales script.',
    salesItems: [
      'Masks, snorkels, fins & booties',
      'Wetsuits, hoods, gloves & rash guards',
      'BCDs, regulators & dive computers',
      'Freediving gear & accessories',
      'Tanks, weights & save-a-dive spares',
    ],
    serviceTitle: 'Service',
    serviceText:
      'Keep your life-support gear working the way it should. Our technicians service regulators and BCDs, swap batteries and O-rings, and pressure-check tanks so small problems never become in-water ones.',
    serviceItems: [
      'Annual regulator service & rebuilds',
      'BCD inspection & repair',
      'Dive-computer battery replacement',
      'Tank visual inspection & fills',
      'Wetsuit & drysuit minor repairs',
    ],
    rentalTitle: 'Rental',
    rentalText:
      'Travelling light or trying something before you buy? Rent well-maintained gear by the day or the trip — full sets or single pieces, sized and checked before you leave the shop.',
    rentalItems: [
      'Full scuba sets & individual pieces',
      'Wetsuits in a full range of sizes',
      'Dive computers & torches',
      'Daily, weekend & trip rates',
      'Included with many courses & guided dives',
    ],
    ctaTitle: 'Not sure what you need?',
    ctaText: 'Drop by the shop or message us — we’ll help you find, fit, or fix the right gear.',
  },
  map: {
    title: 'Dive Sites of Taiwan',
    hint: 'Tap a marker or a region below to zoom in.',
    back: '← Back to overview',
    shore: 'Shore',
    boat: 'Boat',
    diveSites: 'Dive sites',
    close: 'Close',
  },
  common: {
    readMore: 'Read more',
    viewOnMap: 'View on map',
    details: 'Details',
    book: 'Book',
    bookNow: 'Book Now',
    register: 'Register',
    joinWaitlist: 'Join waitlist',
    waitlist: 'Waitlist',
    viewAll: 'View all',
    contactUs: 'Contact us',
    from: 'From',
    nothingScheduled: 'Nothing scheduled yet.',
    featured: 'Featured',
    dive: 'Dive',
    course: 'Course',
    loadingDetails: 'Loading details…',
    pendingImage: 'Image coming soon',
  },
  home: {
    featured: 'Featured',
    upcomingDives: 'Upcoming Dives',
    upcomingCourses: 'Upcoming Courses',
    exploreServices: 'Explore our Services',
    exploreServicesIntro:
      'Discover the unique and valuable aspects that make Fun Divers TW the top choice for diving enthusiasts. With our extensive experience and dedication to customer satisfaction, we provide exceptional guided trips and convenient booking services as well as all PADI Recreational Dive Courses.',
    services: [
      {
        title: 'PADI Courses',
        desc: 'Fun Divers Tw offers the full range of PADI Certification Courses, from beginner to professional level! See the courses available here!',
      },
      {
        title: 'Dive Sites',
        desc: 'Fun Divers Tw offers local shore and boat diving trips. There are many beautiful dive sites to visit here on the northeast coast of Taiwan.',
      },
      {
        title: 'Gear Sales, Service, & Rental',
        desc: 'Fun Divers Tw offers a range of Scuba diving and Free diving gear for Sale or Rental. We can also service regulators and BCDs! Contact us to find out more!',
      },
      {
        title: 'International Dive Tours',
        desc: 'Fun Divers Tw plans group tours to a variety of thrilling destinations! Join one of our planned dive trips or let us help you book your customized trip!',
      },
      {
        title: 'Domestic Dive Tours',
        desc: 'Explore the amazing dive destinations around Taiwan with Fun Divers Tw! Join a planned trip or let us help you book a customized trip.',
      },
      {
        title: 'EFR Courses',
        desc: 'Fun Divers Tw offers the full range of EFR courses. Learn how to help yourself and others in an emergency.',
      },
    ],
    divingTitle: 'Diving in Taiwan: Exploring a World Beneath the Waves',
    divingParas: [
      'Taiwan, a treasure trove of cultural heritage and natural beauty, offers diving enthusiasts an unparalleled opportunity to delve into the depths of its azure waters. Taiwan caters to divers year round with dive seasons that vary across the regions. Taiwan is generally divided into three dive regions: The North (including Taipei, Keelung, and Yilan), The South (Lambai and Kenting), and the Outlying Islands (Penghu, Green Island, and Orchid Island).',
      'The season in the north stretches from April until Early October, with the warmest months being July and August. Diving is possible during the winter months, but water temperatures drop to 16-18C and wave conditions can be very unpredictable, which make it very difficult to plan ahead of time.',
      'The dive season in the south, however, is all year, since both Kenting and Lambai (Xiao Liuqiu) are sheltered from all but the worst of the winter winds and storms. The water temperature is warmer than the north, only dropping below 22C from January through March.',
      'The outlying islands, with Penghu situated off the west coast, and Green Island and Orchid Island, nestled off the southeastern coast, beckon adventurers with their own dive seasons. The high season spans from April to November with the low season being December through March. During the high season, water temperatures are warmer (25-30C) and conditions are much calmer while the low season sees cooler waters (18-24C) and more unpredictable wave conditions.',
      "Beyond Taiwan's shores, neighboring paradises like the Philippines and Indonesia offer complementary dive seasons, ensuring that the allure of underwater exploration knows no bounds.",
      "Embark on a journey through Taiwan's dive seasons and beyond, where every descent promises a glimpse into a world of wonder beneath the waves.",
    ],
    taglineMain: 'Breathe the Adventure',
    taglineSub: 'Explore with Confidence',
  },
  getInTouch: {
    title: 'Get In Touch',
    seeCalendar: 'See Full Calendar',
    tryDive: 'Schedule a Try-Dive',
    requestCourse: 'Request a Course',
    name: 'Name',
    email: 'Email',
    request: 'Your Request',
    requestPlaceholder:
      "Dates you're interested in, experience level, anything else we should know...",
    cancel: 'Cancel',
    send: 'Send Request',
    sent: 'Your email app should have opened with your request ready to send. If it didn’t, email {email} directly.',
    orMessage: 'Or message us directly:',
  },
  courses: {
    title: 'PADI Courses',
    subtitle:
      'Learn to dive, level up, or go pro — the full range of PADI recreational courses in Taiwan.',
    upcomingDates: 'Upcoming course dates',
    noDates: 'No scheduled course dates right now — courses also run on request.',
    getInTouch: 'Get in touch',
    enroll: 'Enroll',
  },
  courseDetail: {
    back: '← All courses',
    overview: 'About this course',
    youWillLearn: "What you'll learn",
    quickFacts: 'Course facts',
    prerequisites: 'Prerequisites',
    minAge: 'Minimum age',
    duration: 'Duration',
    depth: 'Max depth',
    certifies: 'You earn',
    upcoming: 'Upcoming dates',
    noDates: 'No scheduled dates right now — this course also runs on request.',
    next: 'Where to next',
    fullPage: 'Full course page',
    cta: 'Ready to start?',
    ctaText: 'Book a date or ask us anything about this course.',
    contact: 'Get in touch',
    notFound: 'That course couldn’t be found.',
  },
  sites: {
    title: 'Dive Sites',
    subtitle:
      'From convenient shore dives in the north to world-class island diving — Taiwan’s underwater highlights.',
    none: 'No dive sites listed yet.',
    loadError: 'Couldn’t load dive sites',
    areas: { Domestic: 'Domestic', International: 'International' },
  },
  siteDetail: {
    back: '← All dive sites',
    overview: 'About this site',
    highlights: 'Highlights',
    marineLife: 'Marine life',
    belowSurface: 'Below the Surface',
    aboveSurface: 'Above the Surface',
    gettingThere: 'How to Get There',
    quickFacts: 'Quick facts',
    depth: 'Depth',
    difficulty: 'Level',
    season: 'Best season',
    waterTemp: 'Water temp',
    visibility: 'Visibility',
    requirements: 'Diver requirements',
    diveType: 'Dive type',
    region: 'Region',
    directions: 'Open in Google Maps',
    morePage: 'Full site page',
    cta: 'Dive this site',
    ctaText: 'See it on our calendar or ask us about a trip.',
    seeCalendar: 'See the calendar',
    contact: 'Get in touch',
    notFound: 'That dive site couldn’t be found.',
  },
  travel: {
    title: 'Dive Travel',
    subtitle: 'Planned group tours and fully customized trips — around Taiwan and beyond.',
    aroundTaiwan: 'Around Taiwan',
    international: 'International Dive Tours',
    loadError: 'Couldn’t load destinations',
    ctaTitle: 'Ready to plan your next trip?',
    ctaText:
      'Check upcoming departures on the calendar, or reach out and we’ll help arrange a custom trip.',
    seeCalendar: 'See the Calendar',
    planCustom: 'Plan a custom trip',
  },
  calendar: {
    title: 'Calendar',
    subtitle:
      'Dives and courses on the schedule. Tap any event for details and to reserve your spot.',
    all: 'All',
    dives: 'Dives',
    courses: 'Courses',
    thisMonth: 'This month',
    noEvents: 'No events scheduled.',
    loadError: 'Couldn’t load the calendar',
    full: 'This event is full — join the waitlist.',
    details: {
      about: 'About this event',
      included: "What's included",
      notIncluded: 'Not included',
      schedule: 'Schedule / itinerary',
      transportation: 'Transportation',
      prerequisites: 'Prerequisites',
      minCert: 'Minimum certification:',
      loggedDives: 'Logged dives:',
    },
  },
  photos: {
    title: 'Photos',
    subtitle: 'A glimpse of life beneath the waves with FunDivers TW.',
    seeMore: 'See more on social',
    follow: 'Follow along for trip recaps, marine life, and behind-the-scenes.',
    sections: { nudibranchs: 'Nudibranchs', reef: 'Reef Life' },
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
  },
  team: {
    title: 'Fun Divers Team',
    subtitle: 'Dedication. Expertise. Passion.',
    visitWebsite: 'Visit website →',
    diveWithUs: 'Dive with us',
    diveWithUsText: 'Questions about a course or trip? We’re happy to help.',
    roles: { idc: 'IDC Staff Instructor', instructor: 'Instructor', divemaster: 'Divemaster' },
  },
  footer: {
    blurb: 'Guided dive trips, PADI courses, and the best dive sites across Taiwan and beyond.',
    contact: 'Contact',
    follow: 'Follow',
    rights: 'Fun Divers Taiwan. All rights reserved.',
    proudly: 'Proudly created with 🤿 ❤️ in Taipei',
    openSource: 'Open source',
    openSourceBlurb: 'We proudly develop FunDive, our open-source dive-shop management software.',
  },
  notFound: {
    code: '404',
    title: 'Page not found',
    text: 'That page has drifted off with the current.',
    back: 'Back to home',
  },
}

/** The shape every language file must have. */
export type Dict = typeof en
