// English — the master copy.
//
// Every other language file mirrors this shape exactly. Add a key here first,
// then add the same key to zh-TW.ts and ja.ts; TypeScript will refuse to build
// until they match, which is how a half-translated site never ships.
//
// Only static UI and marketing copy lives here. Text that comes from the
// database (event titles, schedules) is not translated.

export const en = {
  nav: {
    courses: 'Courses',
    sites: 'Sites',
    map: 'Map',
    photos: 'Photos',
    travel: 'Travel',
    calendar: 'Calendar',
    team: 'Team',
    gear: 'Gear',
    services: 'Services',
  },
  gear: {
    title: 'Gear Sales, Service & Rental',
    subtitle:
      'Everything you need to dive — quality scuba and freediving equipment for sale or rent, plus expert servicing to keep your kit safe and dive-ready.',
    salesTitle: 'Sales',
    salesText:
      'From your first mask and fins to a full technical setup, we help you choose gear that fits you and the way you dive. Try before you buy in-store and get honest advice from working instructors — not a sales script.',
    salesItems: [
      'Masks, snorkels, fins & booties',
      'Wetsuits, hoods, gloves & rash guards',
      'BCDs, regulators & dive computers',
      'Freediving gear & accessories',
      'Tanks, weights & save-a-dive spares',
    ],
    serviceTitle: 'Service',
    serviceText:
      'Keep your life-support gear working the way it should. Our technicians service regulators and BCDs, swap batteries and O-rings, and pressure-check tanks so small problems never become in-water ones.',
    serviceItems: [
      'Annual regulator service & rebuilds',
      'BCD inspection & repair',
      'Dive-computer battery replacement',
      'Tank visual inspection & fills',
      'Wetsuit & drysuit minor repairs',
    ],
    rentalTitle: 'Rental',
    rentalText:
      'Travelling light or trying something before you buy? Rent well-maintained gear by the day or the trip — full sets or single pieces, sized and checked before you leave the shop.',
    rentalItems: [
      'Full scuba sets & individual pieces',
      'Wetsuits in a full range of sizes',
      'Dive computers & torches',
      'Daily, weekend & trip rates',
      'Included with many courses & guided dives',
    ],
    ctaTitle: 'Not sure what you need?',
    ctaText: 'Drop by the shop or message us — we’ll help you find, fit, or fix the right gear.',
  },
  map: {
    title: 'Dive Sites of Taiwan',
    hint: 'Tap a marker or a region below to zoom in.',
    back: '← Back to overview',
    shore: 'Shore',
    boat: 'Boat',
    diveSites: 'Dive sites',
    close: 'Close',
  },
  common: {
    readMore: 'Read more',
    viewOnMap: 'View on map',
    details: 'Details',
    book: 'Book',
    bookNow: 'Book Now',
    register: 'Register',
    joinWaitlist: 'Join waitlist',
    waitlist: 'Waitlist',
    viewAll: 'View all',
    contactUs: 'Contact us',
    from: 'From',
    nothingScheduled: 'Nothing scheduled yet.',
    featured: 'Featured',
    dive: 'Dive',
    course: 'Course',
    loadingDetails: 'Loading details…',
    pendingImage: 'Image coming soon',
  },
  home: {
    featured: 'Featured',
    upcomingDives: 'Upcoming Dives',
    upcomingCourses: 'Upcoming Courses',
    exploreServices: 'Explore our Services',
    exploreServicesIntro:
      'Discover the unique and valuable aspects that make Fun Divers TW the top choice for diving enthusiasts. With our extensive experience and dedication to customer satisfaction, we provide exceptional guided trips and convenient booking services as well as all PADI Recreational Dive Courses.',
    services: [
      {
        title: 'PADI Courses',
        desc: 'Fun Divers Tw offers the full range of PADI Certification Courses, from beginner to professional level! See the courses available here!',
      },
      {
        title: 'Dive Sites',
        desc: 'Fun Divers Tw offers local shore and boat diving trips. There are many beautiful dive sites to visit here on the northeast coast of Taiwan.',
      },
      {
        title: 'Gear Sales, Service, & Rental',
        desc: 'Fun Divers Tw offers a range of Scuba diving and Free diving gear for Sale or Rental. We can also service regulators and BCDs! Contact us to find out more!',
      },
      {
        title: 'International Dive Tours',
        desc: 'Fun Divers Tw plans group tours to a variety of thrilling destinations! Join one of our planned dive trips or let us help you book your customized trip!',
      },
      {
        title: 'Domestic Dive Tours',
        desc: 'Explore the amazing dive destinations around Taiwan with Fun Divers Tw! Join a planned trip or let us help you book a customized trip.',
      },
      {
        title: 'EFR Courses',
        desc: 'Fun Divers Tw offers the full range of EFR courses. Learn how to help yourself and others in an emergency.',
      },
    ],
    divingTitle: 'Diving in Taiwan: Exploring a World Beneath the Waves',
    divingParas: [
      'Taiwan, a treasure trove of cultural heritage and natural beauty, offers diving enthusiasts an unparalleled opportunity to delve into the depths of its azure waters. Taiwan caters to divers year round with dive seasons that vary across the regions. Taiwan is generally divided into three dive regions: The North (including Taipei, Keelung, and Yilan), The South (Lambai and Kenting), and the Outlying Islands (Penghu, Green Island, and Orchid Island).',
      'The season in the north stretches from April until Early October, with the warmest months being July and August. Diving is possible during the winter months, but water temperatures drop to 16-18C and wave conditions can be very unpredictable, which make it very difficult to plan ahead of time.',
      'The dive season in the south, however, is all year, since both Kenting and Lambai (Xiao Liuqiu) are sheltered from all but the worst of the winter winds and storms. The water temperature is warmer than the north, only dropping below 22C from January through March.',
      'The outlying islands, with Penghu situated off the west coast, and Green Island and Orchid Island, nestled off the southeastern coast, beckon adventurers with their own dive seasons. The high season spans from April to November with the low season being December through March. During the high season, water temperatures are warmer (25-30C) and conditions are much calmer while the low season sees cooler waters (18-24C) and more unpredictable wave conditions.',
      "Beyond Taiwan's shores, neighboring paradises like the Philippines and Indonesia offer complementary dive seasons, ensuring that the allure of underwater exploration knows no bounds.",
      "Embark on a journey through Taiwan's dive seasons and beyond, where every descent promises a glimpse into a world of wonder beneath the waves.",
    ],
    taglineMain: 'Breathe the Adventure',
    taglineSub: 'Explore with Confidence',
  },
  getInTouch: {
    title: 'Get In Touch',
    seeCalendar: 'See Full Calendar',
    tryDive: 'Schedule a Try-Dive',
    requestCourse: 'Request a Course',
    name: 'Name',
    email: 'Email',
    request: 'Your Request',
    requestPlaceholder:
      "Dates you're interested in, experience level, anything else we should know...",
    cancel: 'Cancel',
    send: 'Send Request',
    sent: 'Your email app should have opened with your request ready to send. If it didn’t, email {email} directly.',
    orMessage: 'Or message us directly:',
  },
  courses: {
    title: 'PADI Courses',
    subtitle:
      'Learn to dive, level up, or go pro — the full range of PADI recreational courses in Taiwan.',
    upcomingDates: 'Upcoming course dates',
    noDates: 'No scheduled course dates right now — courses also run on request.',
    getInTouch: 'Get in touch',
    enroll: 'Enroll',
  },
  courseDetail: {
    back: '← All courses',
    overview: 'About this course',
    youWillLearn: "What you'll learn",
    quickFacts: 'Course facts',
    prerequisites: 'Prerequisites',
    minAge: 'Minimum age',
    duration: 'Duration',
    depth: 'Max depth',
    certifies: 'You earn',
    upcoming: 'Upcoming dates',
    noDates: 'No scheduled dates right now — this course also runs on request.',
    next: 'Where to next',
    fullPage: 'Full course page',
    cta: 'Ready to start?',
    ctaText: 'Book a date or ask us anything about this course.',
    contact: 'Get in touch',
    notFound: 'That course couldn’t be found.',
  },
  sites: {
    title: 'Dive Sites',
    subtitle:
      'From convenient shore dives in the north to world-class island diving — Taiwan’s underwater highlights.',
    none: 'No dive sites listed yet.',
    loadError: 'Couldn’t load dive sites',
    areas: { Domestic: 'Domestic', International: 'International' },
  },
  siteDetail: {
    back: '← All dive sites',
    overview: 'About this site',
    highlights: 'Highlights',
    marineLife: 'Marine life',
    belowSurface: 'Below the Surface',
    aboveSurface: 'Above the Surface',
    gettingThere: 'How to Get There',
    quickFacts: 'Quick facts',
    depth: 'Depth',
    difficulty: 'Level',
    season: 'Best season',
    waterTemp: 'Water temp',
    visibility: 'Visibility',
    requirements: 'Diver requirements',
    diveType: 'Dive type',
    region: 'Region',
    directions: 'Open in Google Maps',
    morePage: 'Full site page',
    cta: 'Dive this site',
    ctaText: 'See it on our calendar or ask us about a trip.',
    seeCalendar: 'See the calendar',
    contact: 'Get in touch',
    notFound: 'That dive site couldn’t be found.',
  },
  travel: {
    title: 'Dive Travel',
    subtitle: 'Planned group tours and fully customized trips — around Taiwan and beyond.',
    aroundTaiwan: 'Around Taiwan',
    international: 'International Dive Tours',
    loadError: 'Couldn’t load destinations',
    ctaTitle: 'Ready to plan your next trip?',
    ctaText:
      'Check upcoming departures on the calendar, or reach out and we’ll help arrange a custom trip.',
    seeCalendar: 'See the Calendar',
    planCustom: 'Plan a custom trip',
  },
  calendar: {
    title: 'Calendar',
    subtitle:
      'Dives and courses on the schedule. Tap any event for details and to reserve your spot.',
    all: 'All',
    dives: 'Dives',
    courses: 'Courses',
    thisMonth: 'This month',
    noEvents: 'No events scheduled.',
    loadError: 'Couldn’t load the calendar',
    full: 'This event is full — join the waitlist.',
    details: {
      about: 'About this event',
      included: "What's included",
      notIncluded: 'Not included',
      schedule: 'Schedule / itinerary',
      transportation: 'Transportation',
      prerequisites: 'Prerequisites',
      minCert: 'Minimum certification:',
      loggedDives: 'Logged dives:',
    },
  },
  photos: {
    title: 'Photos',
    subtitle: 'A glimpse of life beneath the waves with FunDivers TW.',
    seeMore: 'See more on social',
    follow: 'Follow along for trip recaps, marine life, and behind-the-scenes.',
    sections: { nudibranchs: 'Nudibranchs', reef: 'Reef Life' },
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
  },
  team: {
    title: 'Fun Divers Team',
    subtitle: 'Dedication. Expertise. Passion.',
    visitWebsite: 'Visit website →',
    diveWithUs: 'Dive with us',
    diveWithUsText: 'Questions about a course or trip? We’re happy to help.',
    roles: { idc: 'IDC Staff Instructor', instructor: 'Instructor', divemaster: 'Divemaster' },
  },
  footer: {
    blurb: 'Guided dive trips, PADI courses, and the best dive sites across Taiwan and beyond.',
    contact: 'Contact',
    follow: 'Follow',
    rights: 'Fun Divers Taiwan. All rights reserved.',
    proudly: 'Proudly created with 🤿 ❤️ in Taipei',
    openSource: 'Open source',
    openSourceBlurb: 'We proudly develop FunDive, our open-source dive-shop management software.',
  },
  services: {
    title: 'Managed FunDive for dive shops',
    subtitle: 'We build it. You own it.',
    intro: [
      'FunDive is a free and open-source dive shop management platform, built by divers, for divers.',
      'Unlike traditional software platforms, FunDive does not lock your business into a proprietary system. The software is open source, so you have complete transparency and freedom.',
      'If your shop has the technical skills, you can download FunDive, set it up yourself, and manage it independently.',
      'If you would rather focus on running your dive business than on managing cloud infrastructure, we run it for you.',
    ],
    readTheCode: 'FunDive is open source. Read the code.',

    pricingTitle: 'Simple, transparent pricing',
    setupTitle: 'One-time setup',
    setupBlurb: 'We build and configure your complete FunDive environment.',
    monthlyTitle: 'Managed service',
    monthlyBlurb: 'A flat monthly fee for ongoing maintenance, updates and technical support.',
    perMonth: '/month',
    fromLabel: 'From',
    plainPricing: ['No complicated pricing.', 'No hidden fees.', 'No long-term commitment.'],
    guarantees: ['Cancel anytime', 'Restart anytime', 'No cancellation fees', 'No obligation'],
    guaranteeNote:
      'You keep using the service because it is worth it — not because you are locked in.',

    setupIncludesTitle: 'What we set up for you',
    setupIncludesBlurb:
      'For the one-time setup fee we configure your complete production environment:',
    setupIncludes: [
      'GitHub repository',
      'Supabase project and database',
      'Cloudflare account and DNS',
      'Bitwarden password vault',
      'FunDive deployment',
      'Domain and SSL certificate',
      'Environment settings',
      'Initial system configuration',
    ],
    setupIncludesNote:
      'We take care of the technical details, so your shop starts with a properly configured and secure installation.',

    domainTitle: 'Domain setup',
    domain: [
      'A custom domain gives your FunDive installation a professional web address.',
      'If your shop already owns a domain, we will configure it for FunDive.',
      'If you do not own one yet, we are happy to help you buy and set one up. Registration fees are separate, and depend on the name and the registrar.',
      'Your domain stays owned and controlled by your dive shop.',
    ],

    ongoingTitle: 'Ongoing managed service',
    ongoingBlurb: 'For a flat monthly fee we keep your FunDive installation running smoothly.',
    updatesTitle: 'Updates and maintenance',
    updates: [
      'Installing new FunDive releases',
      'Applying security updates',
      'Updating software dependencies',
      'Keeping the services compatible with each other',
      'Helping with configuration changes',
    ],
    supportTitle: 'Technical support',
    supportBlurb: 'When you need help, you talk directly to the team behind FunDive.',
    support: [
      'Technical troubleshooting',
      'Infrastructure questions',
      'Configuration changes',
      'Deployment problems',
      'General FunDive support',
    ],

    ownershipTitle: 'Your infrastructure. Your data. Your control.',
    ownership: [
      'We believe open-source software should give a business freedom, not a new kind of lock-in.',
      'We build your environment for you, but you own it.',
    ],
    ownsTitle: 'Your dive shop keeps control of',
    owns: [
      'Your FunDive application',
      'Your customer and business data',
      'Your GitHub repository',
      'Your Supabase database',
      'Your Cloudflare account',
      'Your Bitwarden vault and secrets',
      'Your domain and SSL certificate',
    ],
    accessNote:
      'During setup we configure everything for you. Afterwards your shop owns and controls these accounts, and simply grants us the access we need to keep them updated.',
    leavingTitle: 'If you ever stop using our managed service',
    leaving: [
      'Your data remains yours',
      'Your infrastructure remains yours',
      'Your accounts remain yours',
      'You can keep running FunDive yourself',
      'You can hand it to another technical provider',
    ],
    leavingSlogans: ['No proprietary platform.', 'No forced migration.', 'No vendor lock-in.'],

    websitesTitle: 'Full-service dive shop websites',
    websites: [
      'Already have a website that needs improving? We also build and maintain websites for dive shops that want a better presence online.',
      'A dive shop website is often the first impression a customer has, before they book a course, a trip, or a set of gear. We build fast, modern, search-engine-friendly sites designed to bring you more divers.',
    ],
    websiteServiceTitle: 'Website development',
    websiteService: [
      'Design built around search engines',
      'Working with your team on structure, content and branding',
      'Modern layouts that work on any screen',
      'Cloudflare hosting',
      'Fast, secure, low-maintenance deployments',
      'Ongoing improvements and updates',
    ],
    websiteServiceNote:
      'We build them on the same principles as FunDive: reliable infrastructure, modern technology, and full ownership for you.',

    websitePricingTitle: 'Website pricing',
    websiteSetupTitle: 'Website setup',
    websiteSetupIncludes: [
      'Planning and design, together with you',
      'Development and deployment',
      'Cloud infrastructure setup',
      'Domain and SSL certificate',
      'A structure search engines understand',
    ],
    websiteMaintenanceTitle: 'Website maintenance',
    websiteMaintenanceIncludes: [
      'Content updates',
      'Technical maintenance',
      'Security updates',
      'Infrastructure management',
      'Ongoing improvements',
      'Support requests',
    ],
    websitePricingNote:
      'A website needs more back-and-forth and more work specific to your shop, so website projects are priced separately from running FunDive.',

    closingTitle: 'One technology partner for your dive shop',
    closingBlurb:
      'Whether you need a dive shop management system, a website that brings in divers, or someone to keep the lights on, we help you build digital infrastructure you actually own.',
    closing: [
      'Open-source software',
      'Infrastructure owned by you',
      'Set up properly, by people who dive',
      'Support for the long run',
    ],
    slogan: 'We build it. You own it.',
    ctaTitle: 'Talk to us',
    ctaBlurb: 'Tell us about your shop, and we will work out together what you actually need.',
    emailUs: 'Email us',
  },
  notFound: {
    code: '404',
    title: 'Page not found',
    text: 'That page has drifted off with the current.',
    back: 'Back to home',
  },
}

/** The shape every language file must have. */
export type Dict = typeof en
