import type { Dict } from './en'

// 繁體中文. Machine-translated first pass, refine freely.
// The `: Dict` annotation makes TypeScript flag any key you miss.

export const zhTW: Dict = {
  nav: {
    education: '學習',
    community: '社群',
    about: '關於我們',
    goDiving: '去潛水',

    courses: '課程',
    life: '海洋生物',
    quiz: '生物測驗',

    news: '潛水日誌',
    reputation: '口碑',
    fundive: 'FunDive App',

    origins: '起源',
    team: '團隊',

    calendar: '行事曆',
    sites: '潛點',
    map: '地圖',
    travel: '旅遊',
    buildTrip: '自訂行程',

    services: '服務',
    gear: '裝備',
    cycling: '單車導覽',
    hiking: '健行導覽',
    websites: '網站服務',

    // Sits under the logo, in every layout — see Nav.svelte.
    slogan: '呼吸冒險，自信探索。',
    signIn: '登入',
    radio: '廣播節目',
    menu: '切換選單',
    language: '語言',
  },
  gear: {
    title: '裝備銷售、維修與租借',
    subtitle:
      '潛水所需的一切，優質的水肺與自由潛水裝備，可購買或租借，並提供專業維修保養，讓你的裝備隨時安全、隨時可下水。',
    salesTitle: '銷售',
    salesText:
      '從你的第一副面鏡與蛙鞋，到完整的技術潛水配置，我們協助你挑選最適合自己與潛水方式的裝備。可在店內試用，並由現役教練提供誠實建議，而非制式推銷。',
    salesItems: [
      '面鏡、呼吸管、蛙鞋與潛水靴',
      '防寒衣、頭套、手套與防磨衣',
      'BCD、調節器與潛水電腦錶',
      '自由潛水裝備與配件',
      '氣瓶、配重與備用小物',
    ],
    serviceTitle: '維修',
    serviceText:
      '讓你的生命支持裝備維持在最佳狀態。我們的技師維修調節器與 BCD，更換電池與 O 環，並檢測氣瓶壓力，讓小問題不會在水下變成大麻煩。',
    serviceItems: [
      '調節器年度保養與翻修',
      'BCD 檢查與維修',
      '潛水電腦錶更換電池',
      '氣瓶目視檢查與充氣',
      '防寒衣與乾衣小修',
    ],
    rentalTitle: '租借',
    rentalText:
      '輕裝旅行，或想在購買前先試用？可依天數或行程租借保養良好的裝備，整套或單件，出店前皆已調整尺寸並檢查完畢。',
    rentalItems: [
      '整套水肺裝備與單件租借',
      '各種尺寸的防寒衣',
      '潛水電腦錶與手電筒',
      '單日、週末與行程費率',
      '多數課程與帶領潛水已含裝備',
    ],
    ctaTitle: '不確定需要什麼？',
    ctaText: '歡迎到店或傳訊給我們，我們會協助你找到、試穿或維修合適的裝備。',
  },
  map: {
    title: '台灣潛點地圖',
    hint: '點選標記或下方地區以放大。',
    back: '← 返回總覽',
    shore: '岸潛',
    boat: '船潛',
    diveSites: '潛點',
    close: '關閉',
  },
  common: {
    readMore: '了解更多',
    viewOnMap: '查看地圖',
    details: '詳情',
    book: '預約',
    bookNow: '立即預約',
    register: '報名',
    joinWaitlist: '加入候補',
    waitlist: '候補',
    viewAll: '查看全部',
    contactUs: '聯絡我們',
    fromPrice: '{price}起',
    nothingScheduled: '目前尚未安排。',
    featured: '精選',
    dive: '潛水',
    course: '課程',
    adventure: '探險',
    loadingDetails: '載入詳情中…',
    pendingImage: '照片即將上架',
  },
  home: {
    startTitle: '開始潛水',
    startText: '從沒在水下呼吸過？就從這裡開始！',
    startLadder: [
      { label: '開放水域', note: '你在水下的第一口呼吸' },
      { label: '進階開放水域', note: '更深，也包括夜潛' },
      { label: '救援潛水員', note: '當狀況真的發生時' },
      { label: '潛水長', note: '帶團，並邁向專業' },
    ],
    seeLife: '你會看到什麼',
    whereWeDive: '我們在哪裡潛水',
    whoWeAre: '我們是誰',

    comingTitle: '近期活動',
    comingText: '已排定的休閒潛水、船潛行程與探險活動。',
    seeCalendar: '完整行事曆 →',
    communityTitle: '潛店動態',
    noteSurfaceInterval: '我們最近去了哪裡',
    noteRadio: '從潛店現場直播',
    noteReputation: '潛水員怎麼說我們',

    planTitle: '資深潛水員資源',
    planText: '直接告訴你我們下一次何時、在哪裡下水。',

    taglineMain: '盡情探險',
    taglineSub: '安心潛水',
  },
  education: {
    title: '學習',
    subtitle: '學會潛水、潛得更好，並認識水下的每一種生命。',
    coursesTitle: 'PADI 課程',
    coursesDesc: '完整的 PADI 課程體系，從第一次水下呼吸到專業等級，提供中文、英文與日文教學。',
    lifeTitle: '海洋生物',
    lifeDesc: '我們在台灣礁岩與沉船遇見的生物，由自家潛水員拍攝，依種類分門別類。',
    quizTitle: '這是什麼生物？',
    quizDesc: '以整個相簿出題的翻牌測驗。看看在我們公布答案前，你能認出幾種。',
  },

  community: {
    title: '社群',
    subtitle: '圍繞在潛店周圍的人 — 我們做了些什麼，以及他們怎麼看。',
    newsTitle: '潛水日誌',
    newsDesc: '研討會、志工活動、社區推廣與教學 — 潛水與潛水之間，團隊都在忙些什麼。',
    reputationTitle: '口碑',
    reputationDesc:
      '用潛水員自己的話說說我們，以及在我們無法編輯的地方 — Google、Facebook 與 TripAdvisor 上的評論。',
    radioTitle: '廣播節目',
    radioDesc: '我們從潛店現場直播。可以在這裡收聽，或直接用導覽列上的按鈕。',
    fundiveTitle: 'FunDive App',
    fundiveDesc: '在我們的開源潛店應用程式中預約潛水、追蹤課程進度並管理你的報名。',
  },

  goDiving: {
    title: '去潛水',
    subtitle: '挑一個日期、挑一個潛點，或在地圖上畫出屬於你的路線。',
    calendarTitle: '行事曆',
    calendarDesc: '所有已排定的潛水、課程與行程，並可直接預約名額。',
    sitesTitle: '潛點',
    sitesDesc: '從距離台北一小時的岸潛，到世界級的離島陡壁。',
    mapTitle: '地圖',
    mapDesc: '台灣的潛點，依地區分布在一張可以放大的地圖上。',
    travelTitle: '潛水旅遊',
    travelDesc: '台灣與亞洲各地的既定團體潛旅，從頭到尾都替你安排好。',
    buildTripTitle: '自訂行程',
    buildTripDesc: '行事曆上沒有合適的？自己排一份行程，我們替你估價。',
  },

  about: {
    title: '關於我們',
    subtitle: '兩位教練、一間位於永和的潛店，以及大量泡在水裡的時光。',
    originsTitle: '起源',
    originsDesc: '從 2013 年一位教練在自家公寓起步，到兩位對等的共同經營者與一間永和的潛店。',
    teamTitle: '團隊成員',
    teamDesc: '真正和你一起下水的教練與潛水長 — 以及他們各自潛水的理由。',
    storyTitle: 'FunDivers 的起點',
    storyParas: [
      'FunDivers TW 大約始於 2013 年，地點是 Dennis Wong 的公寓。當時還沒有店面，只有幾支氣瓶、一支電話，以及他在那一年剛取得的 PADI 教練證。',
      'Dennis 以前就教過人，只是教的不是潛水。他曾在北海道二世谷擔任滑雪與單板滑雪教練，之後也涉足過活動企劃。潛水則是一路沒斷過：他從 1998 年就開始潛，一開始吸引他的就是成群的魚 — 數百尾同時轉向，彷彿在同一瞬間收到了同一個訊息 — 而在 2013 年，他決定把它變成職業。',
      'Billy Evalt 則是從完全不同的方向走進來的。他曾在軍中擔任語言專才，2008 年經朋友推薦在越南學會潛水，第一支氣瓶還沒用完就已著迷，並於 2012 年取得教練資格。當他人在台北時，正以教英文為業，手上握著教練證，也想開拓別的可能 — 於是他聯絡了 Dennis。',
      '從那時起，兩人一起經營這間店。大約在 2015 到 2016 年間，他們正式把它寫進紙上：對等的共同經營者。',
      '如今潛店以三種語言教授完整的 PADI 課程，全年帶潛台灣本島與離島，規劃跨越亞洲的團體行程，也公開開發自家的潛店管理軟體。Dennis 自 2018 年起擔任 IDC 教練團隊成員，並連續四年獲頒 PADI 菁英教練。做的事變多了，理由卻沒變：我們只是想帶你下去，讓你親眼看看。',
    ],
    staffTitle: '和你一起下水的人',
    staffIntro:
      '每週都在這裡授課的教練與潛水長。問他們為什麼潛水，你會得到不同的答案，而這正是重點。',
    since: '開始潛水',
    interests: '不在水裡的時候',
    why: '我為什麼潛水',
    aboveWater: '水面之上',
    underwater: '水面之下',
    exploreServices: '探索我們的服務',
    exploreServicesIntro:
      '了解讓 Fun Divers TW 成為潛水愛好者首選的獨特之處。憑藉豐富的經驗與對顧客滿意度的堅持，我們提供出色的導潛行程、便捷的預約服務，以及全系列 PADI 休閒潛水課程。',
    services: [
      {
        title: 'PADI 課程',
        desc: 'Fun Divers TW 提供全系列 PADI 認證課程，從初學者到專業等級！在此查看可報名的課程！',
      },
      {
        title: '潛點',
        desc: 'Fun Divers TW 提供在地的岸潛與船潛行程。台灣東北角有許多美麗的潛點等你來探索。',
      },
      {
        title: '裝備銷售、保養與租借',
        desc: 'Fun Divers TW 提供各式水肺與自由潛水裝備銷售或租借，也可保養調節器與 BCD！歡迎洽詢了解更多！',
      },
      {
        title: '國際潛旅',
        desc: 'Fun Divers TW 規劃前往各個精彩目的地的團體行程！參加我們安排好的潛旅，或讓我們協助你規劃客製化行程！',
      },
      {
        title: '國內潛旅',
        desc: '與 Fun Divers TW 一起探索台灣周邊絕美的潛水勝地！參加既定行程，或讓我們協助你規劃客製化行程。',
      },
      {
        title: 'EFR 急救課程',
        desc: 'Fun Divers TW 提供全系列 EFR 課程，學習在緊急時刻幫助自己與他人。',
      },
    ],
    divingTitle: '在台灣潛水：探索波濤之下的世界',
    divingParas: [
      '台灣擁有豐富的文化底蘊與自然之美，為潛水愛好者提供深入碧藍海域的絕佳機會。台灣全年皆可潛水，各地區的潛水季節各有不同。一般將台灣分為三大潛水區域：北部（含台北、基隆、宜蘭）、南部（小琉球與墾丁），以及離島（澎湖、綠島與蘭嶼）。',
      '北部的潛水季從四月延續到十月初，最溫暖的月份為七月與八月。冬季雖仍可潛水，但水溫會降至 16–18°C，且海況難以預測，較難提前安排。',
      '南部則全年皆為潛水季，因為墾丁與小琉球都能避開大部分冬季強風與風浪。水溫也比北部溫暖，僅在一月至三月之間降至 22°C 以下。',
      '離島方面，澎湖位於西岸，綠島與蘭嶼則坐落於東南外海，各有專屬的潛水季節。旺季為四月至十一月，淡季則為十二月至三月。旺季水溫較暖（25–30°C）、海況更為平穩；淡季水溫較涼（18–24°C），海況也較難預測。',
      '在台灣之外，鄰近的菲律賓與印尼等潛水天堂擁有互補的潛水季節，讓水下探索的魅力永無止境。',
      '踏上一段穿越台灣潛水季節與更遠方的旅程，每一次下潛都是窺見波濤之下奇妙世界的機會。',
    ],
  },

  origins: {
    title: '起源',
    subtitle: '這間潛店從哪裡來，又是從哪兩個人開始的。',
  },

  radio: {
    title: 'FunDivers 廣播節目',
    subtitle: '潛水閒聊、音樂，以及當下想到的一切 — 從潛店現場直播。',
    intro: [
      '我們從潛店現場直播：上週末看到了什麼、接下來要去哪裡、偶爾為了裝備爭論幾句，中間再放點音樂。',
      '只有節目進行時才會有串流。其他時間，這個頁面和導覽列上的廣播按鈕都會安靜地告訴你 — 背景不會偷偷載入任何東西。',
    ],
    listen: '收聽直播',
    stop: '停止收聽',
    connecting: '連線中…',
    live: '正在直播',
    offAir: '目前未播出',
    offAirText: '目前沒有節目正在播出。請在節目時間再試一次，或追蹤我們的社群，開播前會先通知。',
    idleText: '按下播放。如果我們正在直播，你就會聽到；沒有的話，畫面也會告訴你。',
    barHint: '導覽列上的廣播按鈕功能相同，在網站的任何頁面都能使用。',
  },

  reputation: {
    title: '口碑',
    subtitle: '潛水員怎麼說我們 — 這裡是他們自己的話，也有我們一個字都無法編輯的公開評論。',
  },

  testimonials: {
    title: '學員心得',
    none: '目前還沒有心得分享。',
    ctaTitle: '和我們潛過水嗎？',
    ctaText: '我們很想知道你的感受 — 寫信給我們，或留下一則公開評論。',
    leaveReview: '留下評論',
    contact: '寄信給我們',
  },

  reviews: {
    title: '評論',
    intro:
      '以下每一則評論都放在別人的平台上，我們無法編輯或隱藏其中任何一個字。歡迎讀一讀 — 如果你曾和我們一起下水，留下你的評論，對一間小潛店真的很有幫助。',
    readReviews: '閱讀評論',
    writeReview: '撰寫評論',
    platforms: {
      google: '三個平台中最熱鬧的一個，也是多數人最先找到的地方。',
      facebook: '來自長期關注潛店動態的潛水員的推薦。',
      tripadvisor: '計畫來台灣潛水的旅客通常會先看這裡。',
    },
  },

  getInTouch: {
    title: '聯絡我們',
    seeCalendar: '查看完整行事曆',
    tryDive: '預約體驗潛水',
    requestCourse: '報名課程諮詢',
    name: '姓名',
    email: '電子郵件',
    request: '您的需求',
    requestPlaceholder: '您感興趣的日期、潛水經驗，或其他想讓我們知道的事…',
    cancel: '取消',
    send: '送出需求',
    sent: '您的郵件程式應已開啟並填好需求內容，等待寄出。若未開啟，請直接寄信至 {email}。',
    orMessage: '或直接傳訊給我們：',
  },
  courses: {
    title: 'PADI 課程',
    subtitle: '學習潛水、提升等級或邁向專業，台灣全系列 PADI 休閒潛水課程。',
    upcomingDates: '近期課程日期',
    noDates: '目前沒有排定的課程日期，課程亦可依需求安排。',
    getInTouch: '與我們聯絡',
    enroll: '報名',
  },
  courseDetail: {
    back: '← 所有課程',
    overview: '課程介紹',
    youWillLearn: '你將學到',
    quickFacts: '課程資訊',
    prerequisites: '先修資格',
    minAge: '最低年齡',
    duration: '時長',
    depth: '最大深度',
    certifies: '取得資格',
    timeFrame: '課程時程',
    materials: '教材',
    recommended: '建議項目',
    equipment: '裝備',
    notes: '注意事項',
    upcoming: '近期日期',
    noDates: '目前沒有排定的日期，本課程亦可依需求安排。',
    next: '接下來',
    fullPage: '完整課程頁面',
    cta: '準備好開始了嗎？',
    ctaText: '預約日期，或詢問我們關於這門課程的任何問題。',
    contact: '與我們聯絡',
    notFound: '找不到這門課程。',
  },
  sites: {
    title: '潛點',
    subtitle: '從北部便利的岸潛到世界級的離島潛水，台灣水下的精華亮點。',
    none: '尚未列出任何潛點。',
    loadError: '無法載入潛點',
    areas: { Domestic: '國內', International: '國際' },
  },
  siteDetail: {
    back: '← 所有潛點',
    overview: '潛點介紹',
    highlights: '亮點',
    marineLife: '海洋生物',
    belowSurface: '水面下',
    aboveSurface: '水面上',
    gettingThere: '如何前往',
    quickFacts: '重點資訊',
    depth: '深度',
    difficulty: '等級',
    season: '最佳季節',
    waterTemp: '水溫',
    visibility: '能見度',
    requirements: '潛水員資格',
    diveType: '潛水類型',
    region: '區域',
    directions: '在 Google 地圖開啟',
    cta: '來潛這個點',
    ctaText: '在行事曆上查看，或詢問我們的行程。',
    seeCalendar: '查看行事曆',
    contact: '聯絡我們',
    notFound: '找不到這個潛點。',
  },
  travel: {
    title: '潛旅',
    subtitle: '既定團體行程與完全客製化的旅程，台灣與更遠的地方。',
    aroundTaiwan: '台灣周邊',
    international: '國際潛旅',
    loadError: '無法載入目的地',
    ctaTitle: '準備好規劃下一趟旅程了嗎？',
    ctaText: '在行事曆查看近期出團，或與我們聯絡，協助你安排客製化行程。',
    seeCalendar: '查看行事曆',
    planCustom: '規劃客製化行程',
  },
  calendar: {
    title: '行事曆',
    subtitle: '潛水、課程與探險行程一覽。點選任一活動查看詳情並預約名額。',
    all: '全部',
    dives: '潛水',
    courses: '課程',
    thisMonth: '本月',
    noEvents: '尚無排定的活動。',
    noCoursesInRange: '此期間沒有課程。',
    loadError: '無法載入行事曆',
    full: '此活動已額滿，請加入候補名單。',
    toggleDives: '切換潛水顯示',
    toggleAdventures: '切換探險顯示',
    filterCourses: '篩選課程',
    prevMonth: '上個月',
    nextMonth: '下個月',
    details: {
      about: '活動介紹',
      included: '費用包含',
      notIncluded: '費用不含',
      schedule: '行程／時程',
      transportation: '交通',
      prerequisites: '報名條件',
      minCert: '最低證照等級：',
      loggedDives: '潛水紀錄支數：',
    },
  },
  photos: {
    title: '海洋生物',
    subtitle: '水下住著什麼 — 全部拍攝自我們自己的潛水，一種一種介紹。',
    seeMore: '在社群看更多',
    follow: '追蹤我們，看行程回顧、海洋生物與幕後花絮。',
    comingSoon: '照片即將上線',
    jumpTo: '跳至分類',
    photoCount: '張照片',
    meta: {
      species: '學名',
      commonName: '俗名',
      site: '潛點',
      taken: '拍攝日期',
      depth: '深度',
      camera: '相機',
      lens: '鏡頭',
      settings: '拍攝設定',
      photographer: '攝影',
    },
    close: '關閉',
    prev: '上一張',
    next: '下一張',
  },
  quiz: {
    title: '這是什麼生物？',
    subtitle: '看照片、猜一猜、再看答案。相簿裡的每張照片隨機出題，看看你能認出幾種。',
    linkFromPhotos: '來測驗一下 →',
    tapToReveal: '想到答案就點一下照片',
    reveal: '看答案',
    hideAgain: '收起來',
    next: '下一張',
    prev: '上一張',
    shuffle: '重新洗牌',
    progress: '第 {n} 張，共 {total} 張',
    seeInGallery: '看更多這類生物 →',
    empty: '目前還沒有可以出題的相簿照片。',
    backToPhotos: '回到相簿',
  },
  team: {
    title: '我們的團隊',
    subtitle: '專注。專業。熱情。',
    visitWebsite: '造訪網站 →',
    diveWithUs: '與我們一起潛水',
    diveWithUsText: '對課程或行程有任何疑問？我們很樂意協助。',
    roles: { idc: 'IDC 資深教練', instructor: '教練', divemaster: '潛水長' },
  },
  news: {
    title: '潛水日誌',
    subtitle: '研討會、志工活動、社區推廣與教學 — 潛水與潛水之間，FunDivers 團隊的近期動態。',
    none: '目前還沒有消息，敬請期待。',
    notFound: '找不到這篇文章。',
    backToAll: '所有文章',
    kinds: {
      conference: '研討會',
      volunteering: '志工活動',
      outreach: '社區推廣',
      education: '教育推廣',
    },
  },
  footer: {
    blurb: '導潛行程、PADI 課程，以及台灣與更遠方最棒的潛點。',
    contact: '聯絡',
    follow: '追蹤',
    more: '更多',
    rights: 'Fun Divers Taiwan 版權所有。',
    proudly: '由 FunDivers {team}在台灣台北用心打造',
    team: '團隊',
    openSource: '開源專案',
    openSourceBlurb: '我們自豪地開發 FunDive，我們的開源潛水店管理軟體。',
    openSourceAria: 'FunDive：我們的開源潛店管理軟體（GitHub）',
    fundiveAlt: 'FunDive 潛店管理軟體',
  },
  fundive: {
    title: '為潛水店打造的 FunDive 託管服務',
    subtitle: '我們負責建置，您擁有一切。',
    intro: [
      'FunDive 是一套免費且開源的潛水店管理平台，由潛水人為潛水人打造。',
      '與傳統的軟體平台不同，FunDive 不會把您的生意鎖進專有系統。軟體是開源的，因此您擁有完全的透明度與自由。',
      '如果貴店具備技術能力，您可以自行下載 FunDive、自行架設、自行管理。',
      '如果您寧願把心力放在經營潛水事業，而不是管理雲端基礎設施，那就交給我們來運作。',
    ],
    readTheCode: 'FunDive 是開源的，歡迎閱讀原始碼。',

    pricingTitle: '簡單、透明的價格',
    setupTitle: '一次性建置',
    setupBlurb: '我們為您建置並設定完整的 FunDive 環境。',
    monthlyTitle: '託管服務',
    monthlyBlurb: '固定月費，包含持續的維護、更新與技術支援。',
    perMonth: '／月',
    plainPricing: ['沒有複雜的計價。', '沒有隱藏費用。', '沒有長期綁約。'],
    guarantees: ['隨時取消', '隨時重啟', '無取消費用', '無任何義務'],
    guaranteeNote: '您繼續使用這項服務，是因為它值得，而不是因為被綁住。',

    setupIncludesTitle: '我們為您建置的內容',
    setupIncludesBlurb: '一次性建置費用包含完整的正式環境設定：',
    setupIncludes: [
      'GitHub 儲存庫',
      'Supabase 專案與資料庫',
      'Cloudflare 帳號與 DNS',
      'Bitwarden 密碼保險庫',
      'FunDive 部署',
      '網域與 SSL 憑證',
      '環境設定',
      '系統初始設定',
    ],
    setupIncludesNote: '技術細節由我們處理，讓貴店從一開始就擁有設定正確且安全的系統。',

    domainTitle: '網域設定',
    domain: [
      '自訂網域讓您的 FunDive 擁有專業的網址。',
      '如果貴店已經擁有網域，我們會協助設定給 FunDive 使用。',
      '如果尚未擁有，我們很樂意協助您購買與設定。網域註冊費用另計，依名稱與註冊商而定。',
      '網域始終由貴店擁有並掌控。',
    ],

    ongoingTitle: '持續的託管服務',
    ongoingBlurb: '以固定月費，我們讓您的 FunDive 穩定運作。',
    updatesTitle: '更新與維護',
    updates: [
      '安裝新版 FunDive',
      '套用安全性更新',
      '更新軟體相依套件',
      '維持各項服務之間的相容性',
      '協助調整設定',
    ],
    supportTitle: '技術支援',
    supportBlurb: '需要協助時，您直接與開發 FunDive 的團隊對話。',
    support: ['技術疑難排解', '基礎設施問題', '設定變更', '部署問題', 'FunDive 一般支援'],

    ownershipTitle: '您的基礎設施。您的資料。您的掌控權。',
    ownership: [
      '我們相信開源軟體應該帶給企業自由，而不是另一種形式的綁定。',
      '環境由我們建置，但它屬於您。',
    ],
    ownsTitle: '貴店始終掌控',
    owns: [
      '您的 FunDive 應用程式',
      '您的顧客與營運資料',
      '您的 GitHub 儲存庫',
      '您的 Supabase 資料庫',
      '您的 Cloudflare 帳號',
      '您的 Bitwarden 保險庫與密鑰',
      '您的網域與 SSL 憑證',
    ],
    accessNote:
      '建置期間由我們完成所有設定。之後這些帳號由貴店擁有並掌控，只需授予我們維護所需的權限即可。',
    leavingTitle: '如果您決定停止使用我們的託管服務',
    leaving: [
      '資料仍然是您的',
      '基礎設施仍然是您的',
      '帳號仍然是您的',
      '您可以自行繼續運作 FunDive',
      '您可以交給其他技術供應商',
    ],
    leavingSlogans: ['沒有專有平台。', '沒有被迫遷移。', '沒有廠商綁定。'],

    closingTitle: '真正屬於您的軟體',
    closingBlurb:
      '無論貴店自行運作 FunDive，或交由我們託管，軟體、資料，以及運行它的基礎設施，所有權都完全屬於您。',
    closing: ['開源軟體', '基礎設施屬於您', '由潛水人親手正確建置', '長期的支援'],
    slogan: '我們負責建置，您擁有一切。',
    ctaTitle: '與我們聊聊',
    ctaBlurb: '告訴我們貴店的情況，我們一起釐清您真正需要什麼。',
    emailUs: '寄信給我們',
  },

  websites: {
    title: '潛水店網站全套服務',
    subtitle: '快速、現代的網站，為您帶來更多潛水人。',
    intro: [
      '已經有網站但想要更好？我們也為潛水店建置與維護網站，提升線上能見度。',
      '在顧客報名課程、行程或購買裝備之前，潛水店的網站往往是他們的第一印象。我們打造快速、現代、對搜尋引擎友善的網站，為您帶來更多潛水人。',
    ],
    serviceTitle: '網站開發',
    service: [
      '以搜尋引擎為核心的設計',
      '與您的團隊共同規劃結構、內容與品牌',
      '適應各種螢幕的現代版面',
      'Cloudflare 主機架構',
      '快速、安全、低維護的部署',
      '持續的改進與更新',
    ],
    serviceNote:
      '我們以與 FunDive 相同的原則打造：可靠的基礎設施、現代的技術，以及完全屬於您的所有權。',
    pricingTitle: '網站價格',
    fromLabel: '起',
    perMonth: '／月',
    setupTitle: '網站建置',
    setupIncludes: [
      '與您一同規劃與設計',
      '開發與部署',
      '雲端基礎設施建置',
      '網域與 SSL 憑證',
      '搜尋引擎理解得了的網站結構',
    ],
    maintenanceTitle: '網站維護',
    maintenanceIncludes: [
      '內容更新',
      '技術維護',
      '安全性更新',
      '基礎設施管理',
      '持續改進',
      '支援需求',
    ],
    pricingNote:
      '網站需要更多往返討論、更多針對貴店的客製工作，因此網站專案與 FunDive 託管分開計價。',
    slogan: '我們負責建置，您擁有一切。',
    ctaTitle: '與我們聊聊',
    ctaBlurb: '告訴我們貴店的情況與想要的網站，我們一起把它規劃出來。',
    emailUs: '寄信給我們',
  },

  services: {
    title: '我們的服務',
    subtitle: '潛水、器材、旅遊，以及背後支撐這一切的軟體。',
    gearTitle: '器材銷售、保養與租借',
    gearDesc: '選購、租借，或交由我們保養您的水肺與自由潛水器材。',
    cyclingTitle: '台北單車導覽',
    cyclingDesc: '騎上單車，展開 6 小時的歡樂、陽光、運動與歷史，穿梭台北街頭。',
    hikingTitle: '台北健行導覽',
    hikingDesc: '由嚮導帶路登上台北群山，走訪森林步道與無敵的城市天際線美景。',
    fundiveTitle: '給潛水店的 FunDive',
    fundiveDesc: '開源的潛水店管理軟體。我們負責建置，您完全擁有。',
    websitesTitle: '網站開發',
    websitesDesc: '為潛水店打造的快速、現代、對搜尋引擎友善的網站。',
    learnMore: '了解更多',
  },

  cycling: {
    title: '台北單車導覽',
    subtitle: '6 小時的歡樂、陽光、運動與歷史。',
    intro: [
      '台北，就該從單車座墊上細細品味。專人導覽帶您用整整六個小時騎行城市，一邊輕鬆踩踏，一邊聆聽街道背後的故事。',
      '這是悠閒的一天：好夥伴、新鮮空氣、適度的運動，還有一路上對這座城市與歷史的真切感受。',
    ],
    highlightsTitle: '這一天的內容',
    highlights: [
      { label: '歡樂', text: '親切的導覽與好夥伴相伴，輕鬆愜意的騎行。' },
      { label: '陽光', text: '一整天在戶外，在開闊的空氣中盡情感受城市。' },
      { label: '運動', text: '騎著單車的悠閒六小時——是移動，不是競速。' },
      { label: '歷史', text: '台北街道、廟宇與地標背後的故事。' },
    ],
    ctaTitle: '準備出發了嗎？',
    ctaText: '來信即可預約台北單車導覽，或詢問可預約日期與團體人數。',
    emailUs: '來信洽詢',
  },

  hiking: {
    title: '台北健行導覽',
    subtitle: '由嚮導帶路，走訪台北最美的觀景點與步道。',
    intro: [
      '跟著我們走出城市、走進山林。台北四面環山，往往只需短短一段登山路，就能將街道換成鳥鳴、森林，以及令人難忘的城市天際線。',
      '我們的嚮導健行適合各種體能程度——輕鬆的一個上午，有好夥伴、新鮮空氣，以及沿途的步道故事。',
    ],
    hikesTitle: '我們的健行路線',
    ctaTitle: '準備好出發了嗎？',
    ctaText: '來信即可預約嚮導健行，或詢問可預約日期與團體人數。',
    emailUs: '來信洽詢',
  },

  octopus: {
    dismiss: '關閉',
    trip: { prompt: '找不到想要的行程？', cta: '打造專屬行程！' },
    news: { prompt: '我們最近很忙。', cta: '看看我們的近況' },
    event: { prompt: '即將登場：' },
    fundive: { prompt: '我們開發開源的潛店管理軟體。', cta: '認識 FunDive' },
  },

  arcade: {
    title: '達飛的墨水危機',
    subtitle: '你找到達飛了——瘋潛水的章魚吉祥物。他今天心情不太好，快用墨水擋開那些亂飄的潛水員。',
    hidden: '章魚達飛——玩他的小遊戲',
    start: '開始',
    resume: '繼續',
    again: '再玩一次',
    paused: '暫停',
    over: '墨水用完了',
    score: '分數',
    best: '最佳',
    wave: '關卡',
    lives: '生命',
    keys: '方向鍵或 A／D 轉向 · W 或 ↑ 前進 · 空白鍵噴墨 · P 暫停',
    touch: '用下面的按鈕轉向、前進和噴墨。',
    left: '左轉',
    right: '右轉',
    thrust: '前進',
    fire: '噴墨',
    pause: '暫停',
    backHome: '回到水面',
    taunts: [
      '旁邊一堆中性浮力控制不了的潛水員！',
      '小心！一群不看路的潛水員飄過來了！',
      '又是一臉蛙鞋。每個週末都這樣。',
      '有人要不要先做個浮力檢查？有人嗎？',
      '你踢的那個是我家，謝謝。',
      '八隻手，沒有一隻是水面浮標。',
      '拜託，我先來的，早了大概三億年。',
      '墨水很貴的，你知道吧。',
    ],
  },

  buildTrip: {
    title: '打造你的專屬行程',
    subtitle: '沒看到想要的行程？從我們所有的潛點中，設計你自己的潛水行程，我們協助你實現。',
    intro: '將潛點加入每日行程、設定每處的潛水次數，再送出給我們。我們會回覆日期、交通安排與報價。',
    sitesTitle: '從我們的潛點中挑選',
    taiwan: '南台灣',
    international: '國際',
    add: '加入',
    yourTrip: '你的行程',
    day: '第 {n} 天',
    addDay: '新增一天',
    removeDay: '移除這天',
    activeDayHint: '新增的潛點會加到這天',
    emptyDay: '尚無潛點——從清單加入吧。',
    emptyTrip: '你的行程還是空的。從清單加入潛點開始規劃吧。',
    moveUp: '上移',
    moveDown: '下移',
    remove: '移除',
    yourDetails: '你的資料（選填）',
    name: '姓名',
    email: '電子郵件',
    dates: '希望日期',
    groupSize: '團體人數',
    notes: '還有什麼想告訴我們的嗎？',
    send: '送出行程需求',
    needSites: '請先加入至少一個潛點。',
    unitDays: '天',
    unitDives: '次潛水',
    unitSites: '個潛點',
  },

  notFound: {
    code: '404',
    title: '找不到頁面',
    text: '這個頁面隨著洋流漂走了。',
    back: '回到首頁',
  },
}
